In [2]:
import pandas as pd


CEFR_Dataset = pd.read_csv(r"C:\Grad_Project\Models\Datasets\cefr_leveled_texts.csv")


print("Columns in the dataset:")
print(CEFR_Dataset.columns.tolist())
print("\nShape:", CEFR_Dataset.shape)


display(CEFR_Dataset.head(10))

Columns in the dataset:
['text', 'label']

Shape: (1494, 2)

                                                text label
0  Hi!\nI've been meaning to write for ages and f...    B2
1  ﻿It was not so much how hard people found the ...    B2
2  Keith recently came back from a trip to Chicag...    B2
3  The Griffith Observatory is a planetarium, and...    B2
4  -LRB- The Hollywood Reporter -RRB- It's offici...    B2
5  There can be different kinds of entertainment ...    B2
6  ﻿Facebook has lost millions of users per month...    B2
7  Passover is a Jewish holiday that remembers an...    B2
8  Stephanie recently took a weekend trip to Los ...    B2
9  -LSB- Breaking news alert, 6:23 a.m. GMT -LRB-...    B2

In [ ]:
possible_level_columns = ['level', 'cefr_level', 'CEFR', 'label', 'proficiency', 'Level']

level_col = None
for col in possible_level_columns:
    if col in CEFR_Dataset.columns:
        level_col = col
        break

if level_col is None:
    print("Level column not found! Please rename it manually.")
else:
    print(f"\nCEFR level column found: '{level_col}'")
    
    print("\nLevel distribution:")
    print(CEFR_Dataset[level_col].value_counts().sort_index())
    
    CEFR_Dataset = CEFR_Dataset.rename(columns={level_col: 'level', 
                            CEFR_Dataset.columns[0]: 'text'})  
    
    print("\nRenamed columns → 'text' and 'level'")
    print("Final columns:", CEFR_Dataset.columns.tolist())
    print("\nFinal level distribution:")
    print(CEFR_Dataset['level'].value_counts().sort_index())

CEFR level column found: 'label'

Level distribution:
label
A1    288
A2    272
B1    205
B2    286
C1    241
C2    202
Name: count, dtype: int64

Renamed columns → 'text' and 'level'
Final columns: ['text', 'level']

Final level distribution:
level
A1    288
A2    272
B1    205
B2    286
C1    241
C2    202
Name: count, dtype: int64

In [5]:
import pandas as pd


CEFR_Dataset = pd.read_csv(r"C:\Grad_Project\Models\Datasets\merged_cefr_english_datasets.csv")


print("Columns in the dataset:")
print(CEFR_Dataset.columns.tolist())
print("\nShape:", CEFR_Dataset.shape)


display(CEFR_Dataset.head(10))

Columns in the dataset:
['title', 'lang', 'source_name', 'format', 'category', 'cefr_level', 'license', 'text', 'source_dataset']

Shape: (13869, 9)

,title,lang,source_name,format,category,cefr_level,license,text,source_dataset
0,na,en,readme,sentence-level,reference,C1,CC BY SA NC 4.0,The price elasticity of demand depends on the ...,universalcefr/readme_en
1,na,en,readme,sentence-level,reference,C1,CC BY SA NC 4.0,To find the derivative needed to calculate th...,universalcefr/readme_en
2,na,en,readme,sentence-level,reference,B2,CC BY SA NC 4.0,A cartel is a group of firms that have an expl...,universalcefr/readme_en
3,na,en,readme,sentence-level,reference,B1,CC BY SA NC 4.0,"If both firms select the same category, both ...",universalcefr/readme_en
4,na,en,readme,sentence-level,reference,B1,CC BY SA NC 4.0,The market mechanism is a useful and powerful...,universalcefr/readme_en
5,na,en,readme,sentence-level,reference,C1,CC BY SA NC 4.0,The third stage of the Consumer Decision Makin...,universalcefr/readme_en
6,na,en,readme,sentence-level,reference,B2,CC BY SA NC 4.0,Balance theory Fritz Heider's Balance Theory ...,universalcefr/readme_en
7,na,en,readme,sentence-level,reference,C2,CC BY SA NC 4.0,Peripheral route to persuasion: This aspect of...,universalcefr/readme_en
8,na,en,readme,sentence-level,reference,B1,CC BY SA NC 4.0,Both simple (r outine) and complex decision ma...,universalcefr/readme_en
9,na,en,readme,sentence-level,reference,C1,CC BY SA NC 4.0,"After time, some of these stimuli become adapt...",universalcefr/readme_en

In [6]:
possible_level_columns = ['level', 'cefr_level', 'CEFR', 'label', 'proficiency', 'Level']

level_col = None
for col in possible_level_columns:
    if col in CEFR_Dataset.columns:
        level_col = col
        break

if level_col is None:
    print("Level column not found! Please rename it manually.")
else:
    print(f"\nCEFR level column found: '{level_col}'")
    
    print("\nLevel distribution:")
    print(CEFR_Dataset[level_col].value_counts().sort_index())
    
    CEFR_Dataset = CEFR_Dataset.rename(columns={level_col: 'level', 
                            CEFR_Dataset.columns[0]: 'text'})  
    
    print("\nRenamed columns → 'text' and 'level'")
    print("Final columns:", CEFR_Dataset.columns.tolist())
    print("\nFinal level distribution:")
    print(CEFR_Dataset['level'].value_counts().sort_index())

CEFR level column found: 'cefr_level'

Level distribution:
cefr_level
A1      330
A1+       1
A2     2118
A2+      31
B1     4146
B1+      48
B2     4437
B2+      34
C1     2285
C2      439
Name: count, dtype: int64

Renamed columns → 'text' and 'level'
Final columns: ['text', 'lang', 'source_name', 'format', 'category', 'level', 'license', 'text', 'source_dataset']

Final level distribution:
level
A1      330
A1+       1
A2     2118
A2+      31
B1     4146
B1+      48
B2     4437
B2+      34
C1     2285
C2      439
Name: count, dtype: int64

In [ ]:
import pandas as pd

Dataset_path = r"C:\Grad_Project\Models\Datasets\merged_cefr_english_datasets.csv"
Dataset_path_2 = r"C:\Grad_Project\Models\Datasets\cefr_leveled_texts.csv"

CEFR_Dataset_1 = pd.read_csv(Dataset_path)
CEFR_Dataset_2 = pd.read_csv(Dataset_path_2)


print("Dataset 1 initial columns:", CEFR_Dataset_1.columns.tolist())
print("Dataset 2 initial columns:", CEFR_Dataset_2.columns.tolist())


if 'cefr_level' in CEFR_Dataset_1.columns:
    CEFR_Dataset_1 = CEFR_Dataset_1.rename(columns={'cefr_level': 'level'})
if 'text' not in CEFR_Dataset_1.columns and len(CEFR_Dataset_1.columns) > 0:
    CEFR_Dataset_1 = CEFR_Dataset_1.rename(columns={CEFR_Dataset_1.columns[0]: 'text'})
CEFR_Dataset_1 = CEFR_Dataset_1[['text', 'level']]

if 'label' in CEFR_Dataset_2.columns:
    CEFR_Dataset_2 = CEFR_Dataset_2.rename(columns={'label': 'level'})
if 'text' not in CEFR_Dataset_2.columns and len(CEFR_Dataset_2.columns) > 0:
    CEFR_Dataset_2 = CEFR_Dataset_2.rename(columns={CEFR_Dataset_2.columns[0]: 'text'})
CEFR_Dataset_2 = CEFR_Dataset_2[['text', 'level']]


def clean_level(level):
    if pd.isna(level):
        return level
    level = str(level).strip().upper()  
    level = level.replace('+', '')   
    return level

CEFR_Dataset_1['level'] = CEFR_Dataset_1['level'].apply(clean_level)
CEFR_Dataset_2['level'] = CEFR_Dataset_2['level'].apply(clean_level)


Combined_CEFR_Dataset = pd.concat([CEFR_Dataset_1, CEFR_Dataset_2], ignore_index=True)

print("Columns in the combined dataset:")
print(Combined_CEFR_Dataset.columns.tolist())
print("\nLength of combined dataset:", len(Combined_CEFR_Dataset))
display(Combined_CEFR_Dataset.head(10))


Combined_CEFR_Dataset.drop_duplicates(subset=['text'], inplace=True)
Combined_CEFR_Dataset.dropna(subset=['text', 'level'], inplace=True)
print("\nLength of combined dataset after removing duplicates and NaNs:", len(Combined_CEFR_Dataset))

Valid_Levels = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']
Combined_CEFR_Dataset = Combined_CEFR_Dataset[Combined_CEFR_Dataset['level'].isin(Valid_Levels)]
print("\nLength of combined dataset after filtering valid levels:", len(Combined_CEFR_Dataset))

print("\nFinal level distribution:")
print(Combined_CEFR_Dataset['level'].value_counts().sort_index())

Combined_CEFR_Dataset.to_csv(r"C:\Grad_Project\Models\Datasets\final_combined_cefr_english_dataset.csv", index=False)
print("\nFinal combined dataset saved to 'final_combined_cefr_english_dataset.csv'")

Dataset 1 initial columns: ['title', 'lang', 'source_name', 'format', 'category', 'cefr_level', 'license', 'text', 'source_dataset']
Dataset 2 initial columns: ['text', 'label']
Columns in the combined dataset:
['text', 'level']

Length of combined dataset: 15363

                                                text level
0  The price elasticity of demand depends on the ...    C1
1  To  find the derivative needed to calculate th...    C1
2  A cartel is a group of firms that have an expl...    B2
3  If both firms select the same category,  both ...    B1
4  The market  mechanism is a useful and powerful...    B1
5  The third stage of the Consumer Decision Makin...    C1
6  Balance theory  Fritz Heider's Balance Theory ...    B2
7  Peripheral route to persuasion: This aspect of...    C2
8  Both simple (r outine) and complex decision ma...    B1
9  After time, some of these stimuli become adapt...    C1

Length of combined dataset after removing duplicates and NaNs: 15237

Length of combined dataset after filtering valid levels: 15237

Final level distribution:
level
A1     618
A2    2380
B1    4365
B2    4719
C1    2517
C2     638
Name: count, dtype: int64

Final combined dataset saved to 'final_combined_cefr_english_dataset.csv'

In [ ]:
import pandas as pd
import random
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [19]:
nltk.data.path.append(r"C:\Users\Ahmed Abdel Samad\AppData\Roaming\nltk_data")
nltk.data.path.append(r"C:\nltk_data")

try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt', quiet=False)
try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords', quiet=False)

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

# Load data
df = pd.read_csv(r"C:\Grad_Project\Models\Datasets\final_combined_cefr_english_dataset.csv")
vocab1 = pd.read_csv(r"C:\Grad_Project\Models\Datasets\cefrj-vocabulary-profile-1.5.csv")
vocab2 = pd.read_csv(r"C:\Grad_Project\Models\Datasets\octanove-vocabulary-profile-c1c2-1.0.csv")

vocab1 = vocab1[['headword','pos','CEFR']].dropna(subset=['headword','CEFR'])
vocab2 = vocab2[['headword','pos','CEFR']].dropna(subset=['headword','CEFR'])
vocab1 = vocab1.rename(columns={'headword':'word','CEFR':'level'})
vocab2 = vocab2.rename(columns={'headword':'word','CEFR':'level'})
vocab = pd.concat([vocab1, vocab2], ignore_index=True)
vocab['word'] = vocab['word'].str.lower().str.strip()
vocab['level'] = vocab['level'].str.upper().str.strip()
vocab.drop_duplicates(subset=['word'], inplace=True) 


level_words = {}
for lvl in ['A1','A2','B1','B2','C1','C2']:
    level_words[lvl] = set(vocab[vocab['level']==lvl]['word'].tolist())

print("Level vocabulary sizes:", {k: len(v) for k,v in level_words.items()})

def augment_text(text, level, rate=0.4):
    try:
        tokens = word_tokenize(text)
    except:
        return text
    
    eligible_indices = []
    for i, token in enumerate(tokens):
        word = token.lower()
        if word.isalpha() and word not in stop_words and word in level_words[level]:
            eligible_indices.append((i, token, word))
    
    if not eligible_indices:
        return text
    
    num_replace = max(1, int(len(eligible_indices) * rate))
    to_replace = random.sample(eligible_indices, min(num_replace, len(eligible_indices)))
    
    new_tokens = tokens.copy()
    for idx, original_token, old_word in to_replace:
        candidates = level_words[level] - {old_word}
        if candidates:
            new_word = random.choice(list(candidates))
            if original_token[0].isupper():
                new_word = new_word.capitalize()
            new_tokens[idx] = new_word
    
    return ' '.join(new_tokens)


TARGET = 5000
augmented = []

print("\nFORCING PERFECT BALANCE — 5000 SAMPLES PER LEVEL...")
for level in ['A1','A2','B1','B2','C1','C2']:
    level_df = df[df['level'] == level]
    current = len(level_df)
    needed = TARGET - current
    print(f"{level}: {current} → adding {needed:,} augmented samples...")
    
    samples_pool = level_df['text'].tolist()
    for _ in range(needed):
        original_text = random.choice(samples_pool)
        new_text = augment_text(original_text, level)
        attempts = 0
        while (new_text == original_text or len(new_text) < 20) and attempts < 20:
            new_text = augment_text(original_text, level)
            attempts += 1
        augmented.append({'text': new_text, 'level': level})

# Final dataset
aug_df = pd.DataFrame(augmented)
final_df = pd.concat([df, aug_df], ignore_index=True)
final_df.drop_duplicates(subset='text', inplace=True)
final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)

print("\n" + "="*60)
print("FINAL RESULT — PERFECTLY BALANCED CEFR DATASET")
print("="*60)
print(final_df['level'].value_counts().sort_index())
print("="*60)
print(f"Total samples: {len(final_df):,} → Ready for DistilBERT ≥92% accuracy")

final_df.to_csv(r"C:\Grad_Project\Models\Datasets\PERFECTLY_BALANCED_CEFR_DATASET.csv", index=False)
print(f"SAVED: PERFECTLY_BALANCED_CEFR_DATASET.csv")

Level vocabulary sizes: {'A1': 986, 'A2': 1219, 'B1': 2162, 'B2': 2496, 'C1': 914, 'C2': 876}

FORCING PERFECT BALANCE — 5000 SAMPLES PER LEVEL...
A1: 618 → adding 4,382 augmented samples...
A2: 2380 → adding 2,620 augmented samples...
B1: 4365 → adding 635 augmented samples...
B2: 4719 → adding 281 augmented samples...
C1: 2517 → adding 2,483 augmented samples...
C2: 638 → adding 4,362 augmented samples...

============================================================
FINAL RESULT — PERFECTLY BALANCED CEFR DATASET
============================================================
level
A1     618
A2    2380
B1    4365
B2    4719
C1    2517
C2     638
Name: count, dtype: int64
============================================================
Total samples: 15,237 → Ready for DistilBERT ≥92% accuracy
SAVED: PERFECTLY_BALANCED_CEFR_DATASET.csv

In [ ]:
import pandas as pd


df = pd.read_csv(r"C:\Grad_Project\Models\Datasets\final_combined_cefr_english_dataset.csv")

print(f"Before cleaning: {len(df)} samples")
print(df['level'].value_counts().sort_index())


def is_english(text):
    if not isinstance(text, str):
        return False
   
    non_ascii = sum(1 for c in text if ord(c) > 127)
    return non_ascii / len(text) < 0.15 if text else True


df_clean = df[df['text'].apply(is_english)]
df_clean = df_clean[df_clean['text'].str.len() > 30]  # Remove too short
df_clean = df_clean[df_clean['text'].str.split().str.len() > 8]  # At least 8 words

print(f"After cleaning: {len(df_clean)} samples")
print(df_clean['level'].value_counts().sort_index())


df_clean.to_csv(r"C:\Grad_Project\Models\Datasets\CLEAN_ENGLISH_ONLY_CEFR_DATASET.csv", index=False)
print("SAVED: CLEAN_ENGLISH_ONLY_CEFR_DATASET.csv")

Before cleaning: 15237 samples
level
A1     618
A2    2380
B1    4365
B2    4719
C1    2517
C2     638
Name: count, dtype: int64
After cleaning: 13183 samples
level
A1     392
A2    1492
B1    3732
B2    4500
C1    2432
C2     635
Name: count, dtype: int64
SAVED: CLEAN_ENGLISH_ONLY_CEFR_DATASET.csv

In [ ]:
import pandas as pd
import random
import nltk
import os
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords


nltk_data_dir = r"C:\Users\Ahmed Abdel Samad\AppData\Roaming\nltk_data"
os.makedirs(nltk_data_dir, exist_ok=True)
nltk.data.path.append(nltk_data_dir)


nltk.download('punkt', download_dir=nltk_data_dir, quiet=True)
nltk.download('stopwords', download_dir=nltk_data_dir, quiet=True)


stop_words = set(stopwords.words('english'))


df = pd.read_csv(r"C:\Grad_Project\Models\Datasets\CLEAN_ENGLISH_ONLY_CEFR_DATASET.csv")
print("Original distribution:")
print(df['level'].value_counts().sort_index())


vocab = pd.concat([
    pd.read_csv(r"C:\Grad_Project\Models\Datasets\cefrj-vocabulary-profile-1.5.csv")[['headword','CEFR']],
    pd.read_csv(r"C:\Grad_Project\Models\Datasets\octanove-vocabulary-profile-c1c2-1.0.csv")[['headword','CEFR']]
]).dropna()

vocab['headword'] = vocab['headword'].str.lower().str.strip()
vocab['CEFR'] = vocab['CEFR'].str.upper().str.strip()

level_words = {lvl: list(vocab[vocab['CEFR'] == lvl]['headword']) for lvl in ['A1','A2','B1','B2','C1','C2']}
print("Vocabulary sizes:", {k: len(v) for k, v in level_words.items()})


def augment(text, level):
    words = text.split()
    changed = False
    new_words = words[:]
    
    for i, w in enumerate(words):
        low = w.lower().rstrip('.,!?;:"')
        if low in level_words[level] and low not in stop_words:
            candidates = [c for c in level_words[level] if c != low]
            if candidates and random.random() < 0.4:
                new = random.choice(candidates)
                if w[0].isupper():
                    new = new.capitalize()
                new_words[i] = w[:-len(low)] + new + w[len(low):]
                changed = True
    
    if not changed and len(words) > 5:
        i, j = random.sample(range(len(words)), 2)
        new_words[i], new_words[j] = new_words[j], new_words[i]
        changed = True
    
    return ' '.join(new_words) if changed else text


TARGET = 5000
augmented = []
examples = {l: [] for l in level_words}

print("\nSTARTING FINAL AUGMENTATION — THIS WILL WORK!")

for level in ['A1','A2','B1','B2','C1','C2']:
    current = len(df[df['level'] == level])
    needed = TARGET - current
    if needed <= 0:
        print(f"{level}: {current} (enough)")
        continue
    
    print(f"{level}: {current} → generating {needed:,} samples...")
    pool = df[df['level'] == level]['text'].tolist()
    
    count = 0
    while count < needed:
        new = augment(random.choice(pool), level)
        if new != random.choice(pool):  # simple check
            augmented.append({'text': new, 'level': level})
            count += 1
            if len(examples[level]) < 5:
                examples[level].append((pool[0], new))
            if count % 1000 == 0:
                print(f"   → {count}/{needed}")


final_df = pd.concat([df, pd.DataFrame(augmented)], ignore_index=True)
final_df.drop_duplicates(subset='text', inplace=True)
final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)

print("\n" + "="*80)
print("SUCCESS — DATASET BALANCED!")
print("="*80)
print(final_df['level'].value_counts().sort_index())
print(f"Total: {len(final_df):,}")

final_df.to_csv(r"C:\Grad_Project\Models\Datasets\FINAL_BALANCED_SUCCESS.csv", index=False)
print("SAVED!")

# Print examples
print("\nEXAMPLES:")
for level in examples:
    if examples[level]:
        print(f"\n{level}:")
        o, a = examples[level][0]
        print("Original :", o[:200])
        print("Augmented:", a[:200])

Original distribution:
level
A1     392
A2    1492
B1    3732
B2    4500
C1    2432
C2     635
Name: count, dtype: int64
Vocabulary sizes: {'A1': 1164, 'A2': 1411, 'B1': 2446, 'B2': 2778, 'C1': 1111, 'C2': 1025}

STARTING FINAL AUGMENTATION — THIS WILL WORK!
A1: 392 → generating 4,608 samples...
   → 1000/4608
   → 2000/4608
   → 3000/4608
   → 4000/4608
A2: 1492 → generating 3,508 samples...
   → 1000/3508
   → 2000/3508
   → 3000/3508
B1: 3732 → generating 1,268 samples...
   → 1000/1268
B2: 4500 → generating 500 samples...
C1: 2432 → generating 2,568 samples...
   → 1000/2568
   → 2000/2568
C2: 635 → generating 4,365 samples...
   → 1000/4365
   → 2000/4365
   → 3000/4365
   → 4000/4365

================================================================================
SUCCESS — DATASET BALANCED!
================================================================================
level
A1    4978
A2    4951
B1    4990
B2    4998
C1    4969
C2    4936
Name: count, dtype: int64
Total: 29,822
SAVED!

EXAMPLES:

A1:
Original : Two girls are moving their hands around and then their legs to music.
Augmented: Lulu's bookstore gave Lulu a pencil. It was a yellow ptoilet. It was a never two pencil. It had a pink eraser. The eraser was thirty and round and pink. Lulu's start gave Lulu a piece of ptwelve. It w

A2:
Original : The late 19th century marks the start of psychology as a scientific enterprise.
Augmented: The Purple Centre Whether you are looking for a conference venue or a place to have your meetings and your training days, the Worst Centre is the out of modern blame for your event. Offering free Wi-F

B1:
Original : If both firms select the same category,  both firms lose five million USD, since they have flooded the market with too much  cereal.
Augmented: Millie's sister Arlene had been battling gym cancer for five years. Then the doctor gave Arlene some bad news. The burning had spread to her brain and there was no treatment that would bald her. "I'll

B2:
Original : A cartel is a group of firms that have an explicit agreement to reduce output in order to  increase the price.
Augmented: In drinking water , higher higher the turbidity level , the the the risk that people may develop diseases .

C1:
Original : The price elasticity of demand depends on the availability of substitutes.
Augmented: Several gene families are involved in the processes of hyperaccumulation including sequestration of absorption and upregulation of heavy metal metals .

C2:
Original : Peripheral route to persuasion: This aspect of the Elaboration Likelihood Model identifies  that messages requiring minimal mental processing result in short-term attitude changes,  especially with an
Augmented: Buber’s best-known work is the short philosophical essay I and Thou (1923), the basic tenets of which he was to modify, but never to abandon. In this work, Buber gives expression to the intuition that

In [27]:
df = pd.read_csv(r"C:\Grad_Project\Models\Datasets\FINAL_BALANCED_SUCCESS.csv")

print(f"Length of the dataset: {len(df)}")

Length of the dataset: 29822

In [ ]:
import pandas as pd
import random
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords


nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
stop_words = set(stopwords.words('english'))


df = pd.read_csv(r"C:\Grad_Project\Models\Datasets\final_combined_cefr_english_dataset.csv")
vocab1 = pd.read_csv(r"C:\Grad_Project\Models\Datasets\cefrj-vocabulary-profile-1.5.csv")
vocab2 = pd.read_csv(r"C:\Grad_Project\Models\Datasets\octanove-vocabulary-profile-c1c2-1.0.csv")

vocab1 = vocab1[['headword','pos','CEFR']].dropna(subset=['headword','CEFR'])
vocab2 = vocab2[['headword','pos','CEFR']].dropna(subset=['headword','CEFR'])
vocab1 = vocab1.rename(columns={'headword':'word','CEFR':'level'})
vocab2 = vocab2.rename(columns={'headword':'word','CEFR':'level'})
vocab = pd.concat([vocab1, vocab2], ignore_index=True)
vocab['word'] = vocab['word'].str.lower().str.strip()
vocab['level'] = vocab['level'].str.upper().str.strip()
vocab.drop_duplicates(subset=['word'], inplace=True)

level_words = {}
for lvl in ['A1','A2','B1','B2','C1','C2']:
    level_words[lvl] = set(vocab[vocab['level']==lvl]['word'].tolist())

print("Level vocabulary sizes:", {k: len(v) for k,v in level_words.items()})

def augment_text(text, level, rate=0.4):
    try:
        tokens = word_tokenize(text)
    except:
        return text
    
    eligible_indices = []
    for i, token in enumerate(tokens):
        word = token.lower()
        if word.isalpha() and word not in stop_words and word in level_words[level]:
            eligible_indices.append((i, token, word))
    
    if not eligible_indices:
        return text
    
    num_replace = max(1, int(len(eligible_indices) * rate))
    to_replace = random.sample(eligible_indices, min(num_replace, len(eligible_indices)))
    
    new_tokens = tokens.copy()
    for idx, original_token, old_word in to_replace:
        candidates = level_words[level] - {old_word}
        if candidates:
            new_word = random.choice(list(candidates))
            if original_token[0].isupper():
                new_word = new_word.capitalize()
            new_tokens[idx] = new_word
    
    return ' '.join(new_tokens)


TARGET = 5000
augmented = []
examples_to_show = [] 

print("\nFORCING PERFECT BALANCE — 5000 SAMPLES PER LEVEL...")
for level in ['A1','A2','B1','B2','C1','C2']:
    level_df = df[df['level'] == level]
    current = len(level_df)
    needed = TARGET - current
    print(f"{level}: {current} → adding {needed:,} augmented samples...")
    
    samples_pool = level_df['text'].tolist()
    generated_count = 0
    
    for _ in range(needed):
        original_text = random.choice(samples_pool)
        new_text = augment_text(original_text, level)
        attempts = 0
        while (new_text == original_text or len(new_text) < 20) and attempts < 20:
            new_text = augment_text(original_text, level)
            attempts += 1
        
        augmented.append({'text': new_text, 'level': level})
        generated_count += 1
        
        # Save first 3 real examples per level
        if generated_count <= 3 and len([e for e in examples_to_show if e[2] == level]) < 3:
            examples_to_show.append((original_text, new_text, level))
        
        if generated_count % 1000 == 0:
            print(f"   → {generated_count}/{needed} done for {level}")


aug_df = pd.DataFrame(augmented)
aug_df.to_csv(r"C:\Grad_Project\Models\Datasets\ONLY_AUGMENTED_DATA.csv", index=False)
print(f"\nSAVED ONLY AUGMENTED DATA: ONLY_AUGMENTED_DATA.csv ({len(aug_df):,} samples)")


final_df = pd.concat([df, aug_df], ignore_index=True)
final_df.drop_duplicates(subset='text', inplace=True)
final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)

print("\n" + "="*70)
print("FINAL RESULT — PERFECTLY BALANCED DATASET")
print("="*70)
print(final_df['level'].value_counts().sort_index())
print(f"Total samples: {len(final_df):,}")
print("="*70)

final_df.to_csv(r"C:\Grad_Project\Models\Datasets\PERFECTLY_BALANCED_CEFR_DATASET.csv", index=False)
print("SAVED FULL BALANCED DATASET: PERFECTLY_BALANCED_CEFR_DATASET.csv")


print("\n" + " REAL AUGMENTED EXAMPLES (ONE PER LEVEL) ".center(80, "="))
for orig, aug, lvl in examples_to_show:
    print(f"\nLEVEL {lvl}")
    print("Original :", orig[:300] + "..." if len(orig) > 300 else orig)
    print("Augmented:", aug[:300] + "..." if len(aug) > 300 else aug)
    print("-" * 80)

Level vocabulary sizes: {'A1': 986, 'A2': 1219, 'B1': 2162, 'B2': 2496, 'C1': 914, 'C2': 876}

FORCING PERFECT BALANCE — 5000 SAMPLES PER LEVEL...
A1: 618 → adding 4,382 augmented samples...
   → 1000/4382 done for A1
   → 2000/4382 done for A1
   → 3000/4382 done for A1
   → 4000/4382 done for A1
A2: 2380 → adding 2,620 augmented samples...
   → 1000/2620 done for A2
   → 2000/2620 done for A2
B1: 4365 → adding 635 augmented samples...
B2: 4719 → adding 281 augmented samples...
C1: 2517 → adding 2,483 augmented samples...
   → 1000/2483 done for C1
   → 2000/2483 done for C1
C2: 638 → adding 4,362 augmented samples...
   → 1000/4362 done for C2
   → 2000/4362 done for C2
   → 3000/4362 done for C2
   → 4000/4362 done for C2

SAVED ONLY AUGMENTED DATA: ONLY_AUGMENTED_DATA.csv (14,763 samples)

======================================================================
FINAL RESULT — PERFECTLY BALANCED DATASET
======================================================================
level
A1     618
A2    2380
B1    4365
B2    4719
C1    2517
C2     638
Name: count, dtype: int64
Total samples: 15,237
======================================================================
SAVED FULL BALANCED DATASET: PERFECTLY_BALANCED_CEFR_DATASET.csv

=================== REAL AUGMENTED EXAMPLES (ONE PER LEVEL) ====================

LEVEL A1
Original : Now its over 1500.
Augmented: Now its over 1500.
--------------------------------------------------------------------------------

LEVEL A1
Original : I heard that your brother is in the hospital.
Yeah. He's been there since last week.
Oh, no. What happened? Is he alright?
He got in a car accident. He should be alright.
The doctors told you he would be alright?
Yes, but they need to keep him for further tests.
Oh, okay. I was so worried when I hea...
Augmented: I heard that your brother is in the hospital.
Yeah. He's been there since last week.
Oh, no. What happened? Is he alright?
He got in a car accident. He should be alright.
The doctors told you he would be alright?
Yes, but they need to keep him for further tests.
Oh, okay. I was so worried when I hea...
--------------------------------------------------------------------------------

LEVEL A1
Original : I heard he took on three .
Augmented: I heard he took on three .
--------------------------------------------------------------------------------

LEVEL A2
Original : My best friend's name is Joseph Taylor, but he prefers to be called Joe. He does a lot of stupid stuff, and it usually gets him in trouble. The other day, while he was trying to impress some girls, he fell off his skateboard and broke his arm. Joe had to get his arm in a cast, but he told me it was ...
Augmented: My best friend's name is Joseph Taylor, but he prefers to be called Joe. He does a lot of stupid stuff, and it usually gets him in trouble. The other day, while he was trying to impress some girls, he fell off his skateboard and broke his arm. Joe had to get his arm in a cast, but he told me it was ...
--------------------------------------------------------------------------------

LEVEL A2
Original : She received a ring from her boyfriend .
Augmented: She received a ring from her boyfriend .
--------------------------------------------------------------------------------

LEVEL A2
Original : Tell me what you see .
Augmented: Tell me what you see .
--------------------------------------------------------------------------------

LEVEL B1
Original : Would you mind picking up mine too when you go get your coat ?
Augmented: Would you mind picking up mine too when you go get your coat ?
--------------------------------------------------------------------------------

LEVEL B1
Original : To prevent break-ins , the locks were changed .
Augmented: To prevent break-ins , the locks were changed .
--------------------------------------------------------------------------------

LEVEL B1
Original : Well this is really very nice of you to send me such beautiful flowers .
Augmented: Well this is really very nice of you to send me such beautiful flowers .
--------------------------------------------------------------------------------

LEVEL B2
Original : U.S. Rep. Rahm Emanuel will bring a tough-minded and pragmatic approach to the White House when he becomes President-elect Barack Obama's chief of staff, according to people who know the Chicago, Illinois, native.
Rep. Rahm Emanuel has experience in the White House, on Wall Street and on Capitol Hil...
Augmented: U.S. Rep. Rahm Emanuel will bring a tough-minded and pragmatic approach to the White House when he becomes President-elect Barack Obama's chief of staff, according to people who know the Chicago, Illinois, native.
Rep. Rahm Emanuel has experience in the White House, on Wall Street and on Capitol Hil...
--------------------------------------------------------------------------------

LEVEL B2
Original : Classical cartography has been joined by a more modern approach to geographical analysis, computer-based geographic information systems (GIS).
Augmented: Classical cartography has been joined by a more modern approach to geographical analysis, computer-based geographic information systems (GIS).
--------------------------------------------------------------------------------

LEVEL B2
Original : Running a business in the countryside

Five women talk about their experiences setting up a business in the countryside.

A.
‘My customers are friends,' says CHRISTINE HOGAN, who runs a computer-aided design business with a turnover of over £200,000 a year and four full-time employees. 'My husband...
Augmented: Running a business in the countryside

Five women talk about their experiences setting up a business in the countryside.

A.
‘My customers are friends,' says CHRISTINE HOGAN, who runs a computer-aided design business with a turnover of over £200,000 a year and four full-time employees. 'My husband...
--------------------------------------------------------------------------------

LEVEL C1
Original : Sen. Lisa Murkowski of Alaska Wednesday declared victory over fellow Republican Joe Miller in the nation's last Senate race, saying the result of her write-in candidacy was a miracle.
 Against all odds, we as Alaskans together made history, Murkowski told cheering supporters in Anchorage.
If she pr...
Augmented: Sen. Lisa Murkowski of Alaska Wednesday declared victory over fellow Republican Joe Miller in the nation's last Senate race, saying the result of her write-in candidacy was a miracle.
 Against all odds, we as Alaskans together made history, Murkowski told cheering supporters in Anchorage.
If she pr...
--------------------------------------------------------------------------------

LEVEL C1
Original : Mast cells are a type of innate immune cell in connective tissue and the mucous membranes .
Augmented: Mast cells are a type of innate immune cell in connective tissue and the mucous membranes .
--------------------------------------------------------------------------------

LEVEL C1
Original : In a typical real scenario along the lines of that diagrammed above, B, C and R are all local to a site, and bandwidth of long-haul paths is almost always less than the local LAN bandwidth within a site.
Augmented: In a typical real scenario along the lines of that diagrammed above, B, C and R are all local to a site, and bandwidth of long-haul paths is almost always less than the local LAN bandwidth within a site.
--------------------------------------------------------------------------------

LEVEL C2
Original : Organometallic complexes are commonly used in catalysis .
Augmented: Organometallic complexes are commonly used in catalysis .
--------------------------------------------------------------------------------

LEVEL C2
Original : However , recent research has shown that at least some prokaryotes have microcompartments such as carboxysomes .
Augmented: However , recent research has shown that at least some prokaryotes have microcompartments such as carboxysomes .
--------------------------------------------------------------------------------

LEVEL C2
Original : Siboglinid tube worms , which may grow to over 2 m tall in the largest species , often form an important part of the community around a hydrothermal vent .
Augmented: Siboglinid tube worms , which may grow to over 2 m tall in the largest species , often form an important part of the community around a hydrothermal vent .
--------------------------------------------------------------------------------

In [ ]:
import pandas as pd
import random
import nltk
import os
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords


nltk_data_dir = r"C:\Users\Ahmed Abdel Samad\AppData\Roaming\nltk_data"
os.makedirs(nltk_data_dir, exist_ok=True)
nltk.data.path.append(nltk_data_dir)

nltk.download('punkt', download_dir=nltk_data_dir, quiet=True)
nltk.download('stopwords', download_dir=nltk_data_dir, quiet=True)

stop_words = set(stopwords.words('english'))


df = pd.read_csv(r"C:\Grad_Project\Models\Datasets\final_combined_cefr_english_dataset.csv")
print("Original distribution:")
print(df['level'].value_counts().sort_index())

vocab = pd.concat([
    pd.read_csv(r"C:\Grad_Project\Models\Datasets\cefrj-vocabulary-profile-1.5.csv")[['headword','CEFR']],
    pd.read_csv(r"C:\Grad_Project\Models\Datasets\octanove-vocabulary-profile-c1c2-1.0.csv")[['headword','CEFR']]
]).dropna()

vocab['headword'] = vocab['headword'].str.lower().str.strip()
vocab['CEFR'] = vocab['CEFR'].str.upper().str.strip()

# Build level word lists
level_words = {}
for lvl in ['A1','A2','B1','B2','C1','C2']:
    level_words[lvl] = list(vocab[vocab['CEFR'] == lvl]['headword'])

print("Vocabulary sizes:", {k: len(v) for k, v in level_words.items()})

def augment_text(text, level):
    try:
        tokens = word_tokenize(text)
    except:
        return text
    
    changeable = []
    for i, token in enumerate(tokens):
        word = token.lower().rstrip('.,!?;:"()')
        if (word.isalpha() and 
            word not in stop_words and 
            word in level_words[level]):
            punct = token[len(word):]
            changeable.append((i, token, word, punct))
    
    if len(changeable) < 2:
        return text
    
    num_replace = random.randint(2, min(8, len(changeable)))
    to_replace = random.sample(changeable, num_replace)
    
    new_tokens = tokens.copy()
    for i, old_token, old_word, punct in to_replace:
        candidates = [w for w in level_words[level] if w != old_word and len(w) > 2]
        if candidates:
            new_word = random.choice(candidates)
            if old_token[0].isupper():
                new_word = new_word.capitalize()
            new_tokens[i] = new_word + punct
    
    return ' '.join(new_tokens)


TARGET = 1000    
augmented = []
examples = []

print("\nSTARTING FINAL SUCCESSFUL AUGMENTATION...")

for level in ['A1','A2','B1','B2','C1','C2']:
    current = len(df[df['level'] == level])
    needed = TARGET - current
    if needed <= 0:
        print(f"{level}: {current} (enough)")
        continue
    
    print(f"{level}: {current} → generating {needed:,} samples...")
    pool = df[df['level'] == level]['text'].tolist()
    
    count = 0
    while count < needed:
        orig = random.choice(pool)
        aug = augment_text(orig, level)
        if aug != orig and len(aug) > 30:
            augmented.append({'text': aug, 'level': level})
            count += 1
            if len(examples) < 10:
                examples.append((orig, aug, level))
            if count % 1000 == 0:
                print(f"   → {count}/{needed}")


aug_df = pd.DataFrame(augmented)
aug_df.to_csv(r"C:\Grad_Project\Models\Datasets\ONLY_REAL_AUGMENTED_DATA.csv", index=False)
print(f"\nSAVED ONLY AUGMENTED: {len(aug_df):,} samples")

final_df = pd.concat([df, aug_df], ignore_index=True)
final_df.drop_duplicates(subset='text', inplace=True)
final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)

print("\nSUCCESS!")
print(final_df['level'].value_counts().sort_index())
final_df.to_csv(r"C:\Grad_Project\Models\Datasets\FINAL_PERFECT_BALANCED_DATASET.csv", index=False)

# === PRINT EXAMPLES ===
print("\n" + " REAL AUGMENTED EXAMPLES ".center(80, "="))
for orig, aug, lvl in examples:
    print(f"\nLEVEL {lvl}")
    print("Original :", orig[:300])
    print("Augmented:", aug[:300])
    print("-" * 80)

Original distribution:
level
A1     618
A2    2380
B1    4365
B2    4719
C1    2517
C2     638
Name: count, dtype: int64
Vocabulary sizes: {'A1': 1164, 'A2': 1411, 'B1': 2446, 'B2': 2778, 'C1': 1111, 'C2': 1025}

STARTING FINAL SUCCESSFUL AUGMENTATION...
A1: 618 → generating 382 samples...

In [1]:
import pandas as pd
import random
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import wordnet, stopwords
import os

nltk_data_dir = r"C:\Users\Ahmed Abdel Samad\AppData\Roaming\nltk_data"
os.makedirs(nltk_data_dir, exist_ok=True)
nltk.data.path.append(nltk_data_dir)

nltk.download('punkt', download_dir=nltk_data_dir, quiet=True)
nltk.download('punkt_tab', download_dir=nltk_data_dir, quiet=True)
nltk.download('stopwords', download_dir=nltk_data_dir, quiet=True)
nltk.download('wordnet', download_dir=nltk_data_dir, quiet=True)
nltk.download('omw-1.4', download_dir=nltk_data_dir, quiet=True)

stop_words = set(stopwords.words('english'))

DATA_PATH = r"C:\Grad_Project\Models\Datasets\final_combined_cefr_english_dataset.csv"
VOCAB1_PATH = r"C:\Grad_Project\Models\Datasets\cefrj-vocabulary-profile-1.5.csv"
VOCAB2_PATH = r"C:\Grad_Project\Models\Datasets\octanove-vocabulary-profile-c1c2-1.0.csv"

OUTPUT_AUG = r"C:\Grad_Project\Models\Datasets\FINAL_HIGH_QUALITY_AUGMENTED.csv"
OUTPUT_FINAL = r"C:\Grad_Project\Models\Datasets\FINAL_PERFECT_BALANCED_5000.csv"

df = pd.read_csv(DATA_PATH)
print("Original distribution:")
print(df['level'].value_counts().sort_index())

vocab1 = pd.read_csv(VOCAB1_PATH)[['headword','CEFR']]
vocab2 = pd.read_csv(VOCAB2_PATH)[['headword','CEFR']]

vocab = pd.concat([vocab1, vocab2]).dropna()
vocab['headword'] = vocab['headword'].str.lower().str.strip()
vocab['CEFR'] = vocab['CEFR'].str.upper().str.strip()

level_words = {}
for lvl in ['A1','A2','B1','B2','C1','C2']:
    level_words[lvl] = set(vocab[vocab['CEFR'] == lvl]['headword'])

print("Vocabulary sizes:", {k: len(v) for k, v in level_words.items()})

def get_best_synonyms(word, level):
    best_syns = []
    word_synsets = wordnet.synsets(word)
    if not word_synsets:
        return []
    
    main_synset = word_synsets[0]
    
    for syn in word_synsets:
        for lemma in syn.lemmas():
            s = lemma.name().lower().replace('_', ' ')
            if s != word and s in level_words[level]:
                s_synsets = wordnet.synsets(s)
                if s_synsets:
                    similarity = main_synset.wup_similarity(s_synsets[0])
                    if similarity and similarity > 0.75:  # Very high similarity
                        best_syns.append(s)
    
    return list(set(best_syns))  

def final_augment(text, level):
    tokens = word_tokenize(text)
    new_tokens = tokens.copy()
    
    candidates = []
    for i, token in enumerate(tokens):
        word = token.lower().rstrip('.,!?;:"()[]{}')
        punct = token[len(word):]
        if (word.isalpha() and 
            word not in stop_words and 
            len(word) > 3 and 
            word in level_words[level]):
            syns = get_best_synonyms(word, level)
            if syns:
                candidates.append((i, word, punct, token, syns))
    
    if len(candidates) < 2:
        return text
    
    num_replace = random.randint(2, min(5, len(candidates)))
    chosen = random.sample(candidates, num_replace)
    
    changed = False
    for i, old_word, punct, old_token, syns in chosen:
        new_word = random.choice(syns)
        if old_token[0].isupper():
            new_word = new_word.capitalize()
        new_tokens[i] = new_word + punct
        changed = True
    
    return ' '.join(new_tokens) if changed else text

TARGET = 5000
augmented = []
examples = []

print(f"\n{'='*80}")
print(f"FINAL HIGH-QUALITY SYNONYM AUGMENTATION → TARGET {TARGET} PER CLASS")
print(f"{'='*80}")

for level in ['A1','A2','B1','B2','C1','C2']:
    level_df = df[df['level'] == level]
    current = len(level_df)
    needed = TARGET - current
    if needed <= 0:
        print(f"{level}: {current} (sufficient)")
        continue
    
    print(f"{level}: {current} → generating {needed:,} samples...")
    pool = level_df['text'].tolist()
    count = 0
    
    while count < needed:
        orig = random.choice(pool)
        aug = final_augment(orig, level)
        if aug != orig and len(aug) > 40:
            augmented.append({'text': aug, 'level': level})
            count += 1
            if len(examples) < 10:
                examples.append((orig, aug))
            if count % 1000 == 0:
                print(f"   → {count:,}/{needed:,}")
    
    print(f"{level}: COMPLETED ({count:,} generated)")

# Combine original + augmented
temp_df = pd.concat([df, pd.DataFrame(augmented)], ignore_index=True)

# Remove duplicates
temp_df.drop_duplicates(subset=['text'], inplace=True)

# === FINAL BALANCING: Force exactly 5000 per class ===
print("\n" + "="*80)
print("FINAL BALANCING: ENSURING EXACTLY 5000 SAMPLES PER CLASS")
print("="*80)

balanced_parts = []
for level in ['A1','A2','B1','B2','C1','C2']:
    level_subset = temp_df[temp_df['level'] == level]
    current_count = len(level_subset)
    print(f"{level}: {current_count:,} samples available")
    
    # Resample to exactly 5000 (oversample if <5000, downsample if >5000)
    resampled = level_subset.sample(n=5000, replace=True, random_state=42)
    balanced_parts.append(resampled)

final_df = pd.concat(balanced_parts, ignore_index=True)
final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)  # Shuffle

# Save
final_df.to_csv(OUTPUT_FINAL, index=False)

print(f"\nFINAL PERFECTLY BALANCED DATASET SAVED: {OUTPUT_FINAL}")
print("Final distribution (exactly 5000 per class):")
print(final_df['level'].value_counts().sort_index())
print(f"Total samples: {len(final_df):,}")

print("\n" + " PERFECT HIGH-QUALITY EXAMPLES ".center(80, "="))
for i, (orig, aug) in enumerate(examples):
    print(f"\nExample {i+1}")
    print("Original :", orig[:400])
    print("Augmented:", aug[:400])
    print("-" * 80)

TypeError: Cannot convert numpy.ndarray to numpy.ndarray

In [6]:
import torch
import torch.nn as nn
import torch.optim as optim
from transformers import BertTokenizer, BertModel, BertForMaskedLM
import pandas as pd
import numpy as np
from torch.utils.data import Dataset, DataLoader
import random
import os

# ============================================================================
# FAST HIGH-QUALITY NLP AUGMENTATION USING CONDITIONAL VAE-GAN + BERT
# ============================================================================

# Use the actual path where datasets are stored
BASE_PATH = r"C:\Grad_Project\Models\Datasets"
OUTPUT_PATH = os.path.join(BASE_PATH, "GAN_AUGMENTED_BALANCED.csv")

# Try multiple possible data sources (in order of preference)
POSSIBLE_DATA_FILES = [
    "PERFECTLY_BALANCED_CEFR_DATASET.csv",
    "FINAL_BALANCED_SUCCESS.csv", 
    "FINAL_PERFECT_BALANCED_DATASET.csv",
    "final_combined_cefr_english_dataset.csv",
]


def find_working_dataset():
    """Find the first working dataset file using robust CSV reading"""
    print("Searching for a working dataset...")
    for filename in POSSIBLE_DATA_FILES:
        filepath = os.path.join(BASE_PATH, filename)
        if os.path.exists(filepath):
            print(f"\nTrying: {filename}")
            try:
                # Method 1: Python engine with low_memory=False
                df = pd.read_csv(filepath, engine='python', low_memory=False)
                if 'text' in df.columns and 'level' in df.columns:
                    print(f"✓ Found working dataset: {filename}")
                    print(f"  Loaded {len(df)} rows successfully")
                    return filepath
                else:
                    print(f"✗ Missing 'text' or 'level' columns")
            except Exception as e1:
                # Method 2: Try with explicit dtype
                try:
                    df = pd.read_csv(filepath, dtype={'text': str, 'level': str}, low_memory=False)
                    if 'text' in df.columns and 'level' in df.columns:
                        print(f"✓ Found working dataset: {filename}")
                        print(f"  Loaded {len(df)} rows successfully (method 2)")
                        return filepath
                except Exception as e2:
                    print(f"✗ Failed to read: {str(e1)[:80]}")
    return None


class CEFRTextDataset(Dataset):
    """Dataset for CEFR-leveled texts"""
    def __init__(self, texts, levels, tokenizer, max_len=128):
        self.texts = texts
        self.levels = levels
        self.tokenizer = tokenizer
        self.max_len = max_len
        self.level_map = {'A1': 0, 'A2': 1, 'B1': 2, 'B2': 3, 'C1': 4, 'C2': 5}
    
    def __len__(self):
        return len(self.texts)
    
    def __getitem__(self, idx):
        text = str(self.texts[idx])
        level = self.level_map[self.levels[idx]]
        
        encoding = self.tokenizer(
            text,
            max_length=self.max_len,
            padding='max_length',
            truncation=True,
            return_tensors='pt'
        )
        
        return {
            'input_ids': encoding['input_ids'].squeeze(),
            'attention_mask': encoding['attention_mask'].squeeze(),
            'level': torch.tensor(level, dtype=torch.long)
        }


class ConditionalTextEncoder(nn.Module):
    """Encoder: BERT + VAE encoding with level conditioning"""
    def __init__(self, bert_model, latent_dim=256, num_levels=6):
        super().__init__()
        self.bert = bert_model
        self.hidden_size = bert_model.config.hidden_size
        
        # Level embedding
        self.level_embed = nn.Embedding(num_levels, 64)
        
        # VAE components
        self.fc_mu = nn.Linear(self.hidden_size + 64, latent_dim)
        self.fc_logvar = nn.Linear(self.hidden_size + 64, latent_dim)
        
    def forward(self, input_ids, attention_mask, level):
        # Get BERT embeddings
        outputs = self.bert(input_ids, attention_mask=attention_mask)
        pooled = outputs.pooler_output  # [batch, 768]
        
        # Concatenate with level embedding
        level_emb = self.level_embed(level)  # [batch, 64]
        combined = torch.cat([pooled, level_emb], dim=1)
        
        # VAE encoding
        mu = self.fc_mu(combined)
        logvar = self.fc_logvar(combined)
        
        return mu, logvar


class ConditionalTextGenerator(nn.Module):
    """Generator: Latent → Token logits with level conditioning"""
    def __init__(self, latent_dim=256, vocab_size=30522, max_len=128, num_levels=6):
        super().__init__()
        self.latent_dim = latent_dim
        self.max_len = max_len
        
        self.level_embed = nn.Embedding(num_levels, 64)
        
        # Decoder network
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim + 64, 512),
            nn.LayerNorm(512),
            nn.GELU(),
            nn.Dropout(0.2),
            
            nn.Linear(512, 1024),
            nn.LayerNorm(1024),
            nn.GELU(),
            nn.Dropout(0.2),
            
            nn.Linear(1024, max_len * vocab_size)
        )
        
        self.vocab_size = vocab_size
        
    def forward(self, z, level):
        level_emb = self.level_embed(level)
        combined = torch.cat([z, level_emb], dim=1)
        
        logits = self.decoder(combined)
        logits = logits.view(-1, self.max_len, self.vocab_size)
        
        return logits


class ConditionalDiscriminator(nn.Module):
    """Discriminator: Real/Fake text classifier with level conditioning"""
    def __init__(self, bert_model, num_levels=6):
        super().__init__()
        self.bert = bert_model
        hidden_size = bert_model.config.hidden_size
        
        self.level_embed = nn.Embedding(num_levels, 64)
        
        self.classifier = nn.Sequential(
            nn.Linear(hidden_size + 64, 512),
            nn.LayerNorm(512),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3),
            
            nn.Linear(512, 256),
            nn.LayerNorm(256),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3),
            
            nn.Linear(256, 1),
            nn.Sigmoid()
        )
    
    def forward(self, input_ids, attention_mask, level):
        outputs = self.bert(input_ids, attention_mask=attention_mask)
        pooled = outputs.pooler_output
        
        level_emb = self.level_embed(level)
        combined = torch.cat([pooled, level_emb], dim=1)
        
        return self.classifier(combined)


class FastNLPAugmenter:
    """Complete augmentation system with training and generation"""
    def __init__(self, device='cuda' if torch.cuda.is_available() else 'cpu'):
        self.device = device
        print(f"Using device: {device}")
        self.tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
        
        # Initialize models
        print("Loading BERT models...")
        bert_encoder = BertModel.from_pretrained('bert-base-uncased')
        bert_discriminator = BertModel.from_pretrained('bert-base-uncased')
        
        self.encoder = ConditionalTextEncoder(bert_encoder).to(device)
        self.generator = ConditionalTextGenerator().to(device)
        self.discriminator = ConditionalDiscriminator(bert_discriminator).to(device)
        
        # For quick generation, also use BERT MLM
        self.mlm_model = BertForMaskedLM.from_pretrained('bert-base-uncased').to(device)
        
        # Optimizers
        self.opt_enc = optim.AdamW(self.encoder.parameters(), lr=2e-5)
        self.opt_gen = optim.AdamW(self.generator.parameters(), lr=1e-4)
        self.opt_disc = optim.AdamW(self.discriminator.parameters(), lr=1e-4)
        
    def reparameterize(self, mu, logvar):
        """VAE reparameterization trick"""
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std
    
    def train_step(self, batch):
        """Single training step for the VAE-GAN"""
        input_ids = batch['input_ids'].to(self.device)
        attention_mask = batch['attention_mask'].to(self.device)
        level = batch['level'].to(self.device)
        
        batch_size = input_ids.size(0)
        
        # ==========================
        # Train Discriminator
        # ==========================
        self.opt_disc.zero_grad()
        
        # Real samples
        real_pred = self.discriminator(input_ids, attention_mask, level)
        real_loss = nn.BCELoss()(real_pred, torch.ones_like(real_pred))
        
        # Fake samples
        mu, logvar = self.encoder(input_ids, attention_mask, level)
        z = self.reparameterize(mu, logvar)
        fake_logits = self.generator(z, level)
        fake_ids = torch.argmax(fake_logits, dim=-1)
        fake_mask = (fake_ids != 0).long()
        
        fake_pred = self.discriminator(fake_ids.detach(), fake_mask, level)
        fake_loss = nn.BCELoss()(fake_pred, torch.zeros_like(fake_pred))
        
        d_loss = (real_loss + fake_loss) / 2
        d_loss.backward()
        self.opt_disc.step()
        
        # ==========================
        # Train Generator + Encoder
        # ==========================
        self.opt_enc.zero_grad()
        self.opt_gen.zero_grad()
        
        mu, logvar = self.encoder(input_ids, attention_mask, level)
        z = self.reparameterize(mu, logvar)
        fake_logits = self.generator(z, level)
        
        # Reconstruction loss
        recon_loss = nn.CrossEntropyLoss()(
            fake_logits.reshape(-1, self.generator.vocab_size),
            input_ids.reshape(-1)
        )
        
        # KL divergence
        kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
        kl_loss = kl_loss / batch_size
        
        # GAN loss (fool discriminator)
        fake_ids = torch.argmax(fake_logits, dim=-1)
        fake_mask = (fake_ids != 0).long()
        gen_pred = self.discriminator(fake_ids, fake_mask, level)
        gan_loss = nn.BCELoss()(gen_pred, torch.ones_like(gen_pred))
        
        # Combined loss
        total_loss = recon_loss + 0.1 * kl_loss + 0.5 * gan_loss
        total_loss.backward()
        
        self.opt_enc.step()
        self.opt_gen.step()
        
        return {
            'd_loss': d_loss.item(),
            'recon_loss': recon_loss.item(),
            'kl_loss': kl_loss.item(),
            'gan_loss': gan_loss.item()
        }
    
    def generate_augmented_fast(self, text, level, num_variants=5):
        """
        FAST generation using BERT MLM + conditional sampling
        This is faster than full GAN generation for inference
        """
        self.mlm_model.eval()
        
        variants = []
        tokens = self.tokenizer.tokenize(text)
        
        if len(tokens) == 0:
            return [text] * num_variants
        
        for _ in range(num_variants):
            # Randomly mask 15-30% of tokens
            masked_tokens = tokens.copy()
            num_mask = random.randint(int(len(tokens) * 0.15), int(len(tokens) * 0.3))
            if num_mask == 0:
                num_mask = 1
            mask_indices = random.sample(range(len(tokens)), min(num_mask, len(tokens)))
            
            for idx in mask_indices:
                masked_tokens[idx] = '[MASK]'
            
            # Convert to input
            masked_text = ' '.join(masked_tokens)
            inputs = self.tokenizer(masked_text, return_tensors='pt', 
                                   max_length=128, truncation=True, padding=True)
            inputs = {k: v.to(self.device) for k, v in inputs.items()}
            
            # Generate predictions
            with torch.no_grad():
                outputs = self.mlm_model(**inputs)
                predictions = outputs.logits
            
            # Sample from top-k predictions
            predicted_ids = inputs['input_ids'].clone()
            mask_token_id = self.tokenizer.mask_token_id
            
            for i in range(predicted_ids.size(1)):
                if predicted_ids[0, i] == mask_token_id:
                    probs = torch.softmax(predictions[0, i], dim=-1)
                    # Top-k sampling
                    top_k = torch.topk(probs, k=10)
                    sampled_id = top_k.indices[torch.multinomial(top_k.values, 1)]
                    predicted_ids[0, i] = sampled_id
            
            # Decode
            generated_text = self.tokenizer.decode(predicted_ids[0], skip_special_tokens=True)
            variants.append(generated_text)
        
        return variants


# ============================================================================
# MAIN EXECUTION
# ============================================================================

print("="*80)
print("BERT VAE-GAN DATA AUGMENTER")
print("="*80)

# Find a working dataset
DATA_PATH = find_working_dataset()

if DATA_PATH is None:
    print("\n" + "="*80)
    print("ERROR: NO WORKING DATASET FOUND!")
    print("="*80)
    print("\nPlease run Cell 5 first to create 'final_combined_cefr_english_dataset.csv'")
    print("\nCell 5 combines the base datasets into a clean, unified format.")
    print("\nAfter running Cell 5, run this cell again.")
    print("="*80)
else:
    try:
        # Load the dataset with robust reading
        print(f"\nLoading dataset from: {os.path.basename(DATA_PATH)}")
        
        # Try python engine first
        try:
            df = pd.read_csv(DATA_PATH, engine='python', low_memory=False)
        except:
            # Fallback to explicit dtypes
            df = pd.read_csv(DATA_PATH, dtype={'text': str, 'level': str}, low_memory=False)
        
        # Clean the data
        df = df.dropna(subset=['text', 'level'])
        df['level'] = df['level'].astype(str).str.strip().str.upper()
        df = df[df['level'].isin(['A1', 'A2', 'B1', 'B2', 'C1', 'C2'])]
        
        print(f"Loaded {len(df)} samples")
        print("\nOriginal distribution:")
        print(df['level'].value_counts().sort_index())
        
        # Initialize augmenter
        print("\n" + "="*80)
        print("INITIALIZING VAE-GAN AUGMENTER")
        print("="*80)
        augmenter = FastNLPAugmenter()
        
        # Create dataset
        dataset = CEFRTextDataset(
            df['text'].tolist(),
            df['level'].tolist(),
            augmenter.tokenizer
        )
        
        dataloader = DataLoader(dataset, batch_size=16, shuffle=True)
        
        # Training loop (lightweight - just a few epochs)
        print("\n" + "="*80)
        print("TRAINING VAE-GAN (3 epochs)")
        print("="*80)
        num_epochs = 3
        
        for epoch in range(num_epochs):
            augmenter.encoder.train()
            augmenter.generator.train()
            augmenter.discriminator.train()
            
            total_losses = {'d_loss': 0, 'recon_loss': 0, 'kl_loss': 0, 'gan_loss': 0}
            
            for i, batch in enumerate(dataloader):
                losses = augmenter.train_step(batch)
                for k, v in losses.items():
                    total_losses[k] += v
                
                if i % 50 == 0:
                    print(f"Epoch {epoch+1}/{num_epochs}, Step {i}: " + 
                          ", ".join([f"{k}={v:.4f}" for k, v in losses.items()]))
            
            avg_losses = {k: v/len(dataloader) for k, v in total_losses.items()}
            print(f"\nEpoch {epoch+1} Average Losses: {avg_losses}")
        
        # Fast generation for augmentation
        print("\n" + "="*80)
        print("GENERATING AUGMENTED DATA")
        print("="*80)
        
        TARGET = 5000
        augmented_data = []
        
        for level in ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']:
            level_df = df[df['level'] == level]
            current = len(level_df)
            needed = TARGET - current
            
            if needed <= 0:
                print(f"{level}: {current} samples (sufficient)")
                continue
            
            print(f"{level}: Generating {needed} samples...")
            pool = level_df['text'].tolist()
            count = 0
            
            for i in range(0, needed, 5):  # Generate 5 variants at a time
                orig_text = random.choice(pool)
                variants = augmenter.generate_augmented_fast(orig_text, level, num_variants=5)
                
                for variant in variants:
                    if count >= needed:
                        break
                    if len(variant) > 40 and variant != orig_text:
                        augmented_data.append({'text': variant, 'level': level})
                        count += 1
                
                if count % 500 == 0 and count > 0:
                    print(f"  → {count}/{needed}")
            
            print(f"{level}: COMPLETED ({count} generated)")
        
        # Combine and balance
        final_df = pd.concat([df, pd.DataFrame(augmented_data)], ignore_index=True)
        final_df = final_df.drop_duplicates(subset=['text'])
        
        # Balance to exactly 5000 per class
        balanced_parts = []
        for level in ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']:
            level_subset = final_df[final_df['level'] == level]
            resampled = level_subset.sample(n=5000, replace=True, random_state=42)
            balanced_parts.append(resampled)
        
        final_df = pd.concat(balanced_parts, ignore_index=True)
        final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)
        
        # Save
        final_df.to_csv(OUTPUT_PATH, index=False)
        
        print(f"\n" + "="*80)
        print(f"✓ SAVED: {os.path.basename(OUTPUT_PATH)}")
        print("="*80)
        print("Final distribution:")
        print(final_df['level'].value_counts().sort_index())
        print(f"Total: {len(final_df):,} samples")
        
        # Show examples
        print("\n" + "="*80)
        print("AUGMENTATION EXAMPLES")
        print("="*80)
        for i in range(3):
            orig = random.choice(df['text'].tolist())
            level = random.choice(['A1', 'A2', 'B1', 'B2', 'C1', 'C2'])
            variants = augmenter.generate_augmented_fast(orig, level, num_variants=2)
            
            print(f"\nOriginal ({level}):")
            print(orig[:200])
            print("\nGenerated variants:")
            for j, var in enumerate(variants):
                print(f"  {j+1}. {var[:200]}")
            print("-" * 80)
            
    except Exception as e:
        print(f"\n" + "="*80)
        print(f"ERROR: {e}")
        print("="*80)
        import traceback
        traceback.print_exc()
        print("\n💡 SOLUTION: Run Cell 5 to regenerate the base dataset.")

================================================================================
BERT VAE-GAN DATA AUGMENTER
================================================================================
Searching for a working dataset...

Trying: PERFECTLY_BALANCED_CEFR_DATASET.csv
✗ Failed to read: The 'low_memory' option is not supported with the 'python' engine

Trying: FINAL_BALANCED_SUCCESS.csv
✗ Failed to read: The 'low_memory' option is not supported with the 'python' engine

Trying: FINAL_PERFECT_BALANCED_DATASET.csv
✗ Failed to read: The 'low_memory' option is not supported with the 'python' engine

Trying: final_combined_cefr_english_dataset.csv
✗ Failed to read: The 'low_memory' option is not supported with the 'python' engine

================================================================================
ERROR: NO WORKING DATASET FOUND!
================================================================================

Please run Cell 5 first to create 'final_combined_cefr_english_dataset.csv'

Cell 5 combines the base datasets into a clean, unified format.

After running Cell 5, run this cell again.
================================================================================